// <auto-generated />
using System;
using CarFuel.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarFuel.Services.Migrations
{
    [DbContext(typeof(AppDB))]
    [Migration("20190725044934_update02")]
    partial class update02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarFuel.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color")
                        .HasMaxLength(512);

                    b.Property<DateTime>("DeleteDateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Make")
                        .HasMaxLength(512);

                    b.Property<Guid?>("MemberId");

                    b.Property<string>("Model")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarFuel.Models.FillUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("CarId");

                    b.Property<int?>("NextId");

                    b.Property<double>("liters");

                    b.Property<int>("odometer");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("NextId");

                    b.ToTable("FillUps");
                });

            modelBuilder.Entity("CarFuel.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Lavel")
                        .IsRequired();

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("CarFuel.Models.Car", b =>
                {
                    b.HasOne("CarFuel.Models.Member")
                        .WithMany("Cars")
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("CarFuel.Models.FillUp", b =>
                {
                    b.HasOne("CarFuel.Models.Car")
                        .WithMany("FillUps")
                        .HasForeignKey("CarId");

                    b.HasOne("CarFuel.Models.FillUp", "Next")
                        .WithMany()
                        .HasForeignKey("NextId");
                });
#pragma warning restore 612, 618
        }
    }
}
